// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(CurrencyDbContext))]
    [Migration("20200110140735_Initial_migration")]
    partial class Initial_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AskPrice")
                        .HasColumnType("real")
                        .HasMaxLength(40);

                    b.Property<float>("BidPrice")
                        .HasColumnType("real")
                        .HasMaxLength(40);

                    b.Property<string>("FromCurrencyCode")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("LastRefreshed")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("ToCurrencyCode")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Domain.Entities.CurrencyMonthly", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Published")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Close")
                        .HasColumnType("real")
                        .HasMaxLength(40);

                    b.Property<float>("High")
                        .HasColumnType("real")
                        .HasMaxLength(40);

                    b.Property<float>("Low")
                        .HasColumnType("real")
                        .HasMaxLength(40);

                    b.Property<float>("Open")
                        .HasColumnType("real")
                        .HasMaxLength(40);

                    b.HasKey("Id", "Published");

                    b.ToTable("CurrencyMonthlies");
                });

            modelBuilder.Entity("Domain.Entities.CurrencyMonthly", b =>
                {
                    b.HasOne("Domain.Entities.Currency", "Currency")
                        .WithMany("CurrencyMonthly")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_CurrencyMonthly_Currency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
